[versions]
kotlin = "2.2.21"
kotlinx-serialization = "1.9.0"
kotlinx-coroutines = { strictly = "1.10.2" }
kotlinx-datetime = { strictly = "0.7.1" }

compose = "1.9.4"
compose-material3 = "1.4.0"

java = "22"

extkt = "0.1.5"
optionkt = "0.0.6"

lsafer-compose-simplenav = "0.0.2-rc.2"

# ANDROID
agp = "8.12.3"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"

androidx-activity = "1.11.0"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-lifecycle = "2.9.4"
androidx-cardview = "1.0.0"

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

gradleup-patrouille = { id = "com.gradleup.compat.patrouille", version = "0.1.0" }
gmazzo-buildConfig = { id = "com.github.gmazzo.buildconfig", version = "5.7.0" }

[libraries]

##### Official Dependencies #####

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }

compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }

okio = { module = "com.squareup.okio:okio", version = "3.16.2" }

##### Internal Dependencies #####

optionkt = { module = "net.lsafer.optionkt:optionkt", version.ref = "optionkt" }
extkt-json = { module = "org.cufy.extkt:extkt-json", version.ref = "extkt" }

lsafer-compose-simplenav = { module = "net.lsafer.compose-simplenav:compose-simplenav", version.ref = "lsafer-compose-simplenav" }

##### Community Dependencies #####

touchlab-kermit = { module = "co.touchlab:kermit", version = "2.0.8" }

godaddy-colorpickerCompose = { module = "com.godaddy.android.colorpicker:compose-color-picker", version = "0.7.0" }
skydoves-colorpickerCompose = { module = "com.github.skydoves:colorpicker-compose", version = "1.1.2" } # unused

##### ANDROID Dependencies #####

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "androidx-cardview" }

androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
